language: node_js
sudo: false
node_js:
  - 7
  - 6
  - 4

cache:
  directories:
    - ~/.npm

git:
  depth: 10

branches:
  only:
    - master

before_install:
  - nvm use $TRAVIS_NODE_VERSION
  - npm i -g npm@^5

install:
  - npm i
