language: node_js
sudo: false
node_js:
  - 7
  - 6
  - 4

env:
  - WEBPACK_VERSION=2
  - WEBPACK_VERSION=3
  - WEBPACK_VERSION=4

matrix:
  exclude:
  - node_js: 4
    env: WEBPACK_VERSION=4

cache:
  directories:
    - ~/.npm

git:
  depth: 10

branches:
  only:
    - master

before_install:
  - nvm use $TRAVIS_NODE_VERSION
  - npm i -g npm@^5

install:
  - npm i
  - npm rm webpack
  - npm install webpack@$WEBPACK_VERSION --ignore-scripts || true
