language: node_js
sudo: false
node_js:
  - "4"
  - "6"
cache:
  directories:
    - $HOME/.npm
git:
  depth: 10
branches:
  only:
    - master
before_install:
  - "nvm use $TRAVIS_NODE_VERSION"
  - "npm set loglevel error"
  - "npm set progress false"
  - "npm i -g npm@\"^2.0.0\""
